// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CustomCells
{
	public partial class CustomTVCell : UITableViewCell
	{
        public static readonly NSString Key = new NSString(nameof(CustomTVCell));

        public UIImage ProfileImage
        {
            get => imgView.Image;
            set => imgView.Image = value;
        }

        public string SomeText
        {
            get => myLabel.Text;
            set => myLabel.Text = value;
        }

        public int Section
        {
            get;
            set;
        }

        public int Row
        {
            get;
            set;
        }

		partial void btnNeedHealing(NSObject sender)
		{
            Console.WriteLine($"Im in Row: {Row}, Section: {Section} ");
		}

		public CustomTVCell (IntPtr handle) : base (handle)
		{
		}
	}
}
