// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CustomCells
{
    public partial class TableViewController : UITableViewController
    {
        public TableViewController(IntPtr handle) : base(handle)
        {
        }

        #region TVDataSource

        [Export("numberOfSectionsInTableView:")]
        public nint NumberOfSections(UITableView tableView)
        {
            return 1;
        }

		public override nint RowsInSection(UITableView tableView, nint section)
		{
            return 50;
		}

		public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
		{
            //return base.GetCell(tableView, indexPath);
            var cell = tableView.DequeueReusableCell(CustomTVCell.Key, indexPath) as CustomTVCell;
            cell.SomeText = "I'm ready to unleash my blade!";
            cell.ProfileImage = UIImage.FromFile("genji.png");
            cell.Section = indexPath.Section;
            cell.Row = indexPath.Row;
            return cell;
		}

		#endregion
	}
}
